config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
	# static routes
	get 'statistics' => 'simple#statistics', as: :statistics
	get 'downloads' => 'simple#downloads', as: :downloads
	get 'citation' => 'simple#citation', as: :cite
	get 'about' => 'simple#about', as: :about
	get 'other_database' => 'simple#other_database', as: :other_database
	get 'help' => 'simple#help', as: :help
	get 'home' => 'simple#home', as: :home


	# download route
	get "simple/download_aa_original"
	get "simple/download_nt_original"
	get "simple/download_aa_cus"
	get "simple/download_nt_cus"
	get "simple/download_entry_table_nt_orignal_docx"
	get "simple/download_entry_table_cus"
	get "query/download_new_fasta"
	get "protein/download_filtered_result"
	get "protein/download_filtered_result_fasta"



	match "search" => 'query#search',
		as: :search,
		via: [:get, :post]

	match "result" => 'query#result',
		as: :result,
		via: [:get, :post]

	match "phylogenetic_tree" => 'query#phylogenies',
		as: :phylogenetic_tree,
		via: [:post]

	match "submit_sequence" => "submit_sequence#submit",
		as: :submit_sequence,
		via: [:get, :post]

	match "phylogeny" => "phylogeny#show",
		as: :phylogeny,
		via: [:get, :post]
	
	match "contact" => "contacts#new",
		as: :contact,
		via: [:get, :post]
	resources :contacts, only: [:new, :create]


	resources :protein, only: [:show, :index] do
	end

	resources :compound, only: [:show, :index] do 
	end

	root to: 'simple#home'
end

app/models/query.rb
class Query < ApplicationRecord
end

app/controllers/query_controller.rb
class QueryController < ApplicationController
  # include concerns
  include QueryLogic
  include QueryValidator # concerns is for reducing logic in controller
  include TreeBuilder
  helper QueryHelper # helper is for reducing logic in view



	before_action :set_blast_defaults_for_aa
  

  def search

    # puts "params.inspect => #{params.inspect}"
    if params[:notice].present?
      @error = params[:notice]
    end

    # params.inspect
    params[:filters] ||= {}

    if params[:commit].present?

      if params[:sequence].present?

        # do validation first to make sure the the sequence is ok for blasting
        # then save to query, and send the query id to other actions
        # for the query, make sure the sequenece is delievered properly
        
        # if the sequence is not match /^>/; return true and do making-up
        params_sequence = params[:sequence].clone
        after_validation = validate_amino_acid_sequnence(params_sequence)
        if after_validation.class == String
          params[:sequence] = after_validation
        elsif after_validation.class == Hash
          error_msg = ""
          after_validation.each do |key, error|
            error_msg += "#{error}\n"
          end
          redirect_to :controller => 'query', :action => 'search', params: params.merge(:notice => error_msg ).permit(:notice) and return
        end

      else
        redirect_to :controller => 'query', :action => 'search', params: params.merge(:notice => "Must provide an amino acid sequence in Fasta format").permit(:notice) and return
      end

      fasta_array = params[:sequence].scan(/>[^>]*/)
      # only allow one sequence at time on server
      if fasta_array.length > 1
        redirect_to :controller => 'query', :action => 'search', params: params.merge(:notice => "Please provide only one sequence.").permit(:notice) and return
      end

      # TODO: limit one sequence to send to new tab
      if params[:new_result_tab] == "1"
        # consider render status (for animation) first, then render the result to result page
        redirect_to :controller => 'query', :action => 'result', params: params.merge(:sequence => fasta_array[0],
          :gap_cost => params[:gap_cost], :extend_cost => params[:extend_cost],:mismatch_penalty => params[:mismatch_penalty],
          :match_reward => params[:match_reward], :evalue => params[:evalue], :gapped_alignment => params[:gapped_alignment],
          :filter_query_sequence => params[:filter_query_sequence],:commit => params[:commit]).permit(:sequence, :gap_cost, :extend_cost, 
          :mismatch_penalty, :match_reward, :evalue, :gapped_alignment, :gapped_alignment, :filter_query_sequence, :commit)
      end 


      

      @hits = Hash.new
      @sequences = ActiveSupport::OrderedHash.new
      @new_customized_sequence = CustomizedProteinSequence.new
      protein_sequence = CustomizedProteinSequence.all
      @sequence_group = Hash.new
      protein_sequence.each do |s|
        @sequence_group[s.header] = s.group
      end

      # get list of group and list of organism form protein_sequence
      @group_number_list = Array.new
      @organism_list = Array.new

      # should do one for each request or can do multiple alignment at same time?
      # haven't check for the inapporiate sequence 
      @fasta_seq = fasta_array[0]
      @query = Bio::FastaFormat.new( @fasta_seq )
      query_name = @query.definition
      @sequence = @query.to_seq
      @sequence.auto # Guess the type of sequence. Changes the class of @sequence.
      query_sequence_type = @sequence.seq.class == Bio::Sequence::AA ? 'protein' : 'gene'
      program = @sequence.seq.class == Bio::Sequence::AA ? 'blastp' : 'blastn'
      database = query_sequence_type == 'protein' ? 'reductive_dehalogenase_protein' : 'reductive_dehalogenase_gene'
      # sequence_class = query_sequence_type == 'protein'? ProteinSequence : NucleotideSequence


      blast_options = set_blast_options(program,params)
      blaster = Bio::Blast.local( program, "#{Rails.root}/index/blast/#{database}", blast_options)
      aa_report = blaster.query(@sequence.seq) # @sequence.seq automatically remove the \n; possibly other wildcard

      @aa_similarity =  aa_report.hits().length.to_f / aa_report.db_num().to_f
      @is_exist_chain, @existing_matched_group = get_existing_groups(aa_report,@sequence.seq)
      @aa_sequence_result = generate_hit_array(aa_report,query_name,"protein")
      # load the group
      # hash each header to existing group       => reversed_group_hash
      # hash each group for all avaiable headers => group_hash
      group_hash = Hash.new
      reversed_group_hash = Hash.new
      protein_sequence.each do |single_entry|

        if !@group_number_list.include? single_entry.group
          @group_number_list << single_entry.group
        end
        if !@organism_list.include? single_entry.organism
          @organism_list << single_entry.organism
        end


        if single_entry.group.nil?
          next
        else
          reversed_group_hash[single_entry.header] = single_entry.group
          if group_hash[single_entry.group].nil?
            group_array = Array.new
            group_array << single_entry.header
            group_hash[single_entry.group] = group_array
          else

            group_hash[single_entry.group] << single_entry.header

          end
        end

      end # end protein_sequence.each do |single_entry|


      identity_with_90 = get_identity_by_match(aa_report)
      # puts "identity_with_90 => #{identity_with_90.inspect}"
      @identity_groups = Array.new  # identity_group contains the eligible group number      

      if identity_with_90.length > 0
        identity_with_90.each do |definition|
          group_number = reversed_group_hash[definition]
          if !group_number.blank? && !group_number.nil?
            is_belong_to_group = true
            if group_hash[group_number].length == 1
              # if the group just have one member, then if the query is 90% identical to this member
              # then the query belong to the group
              is_belong_to_group = true

            else
              group_hash[group_number].each do |s_identity|
                if identity_with_90.include? s_identity
                  next
                else
                  is_belong_to_group = false
                end
              end
            end

            if is_belong_to_group == true
              if !@identity_groups.include? group_number
                @identity_groups << group_number
              end
            end 

          end 

        end 

      end
      @identity_groups.concat @existing_matched_group
      @identity_groups = @identity_groups.uniq
      @possible_group_number = get_characterized_member_s(@identity_groups)
    end
  end

  # This is for rendering the result at new page
  def result

    if params[:notice].present?
      @error = params[:notice]
    end

    if params[:commit].present?

      if params[:sequence].present?
        params_sequence = params[:sequence].clone
        after_validation = validate_amino_acid_sequnence(params_sequence)
        if after_validation.class == String
          params[:sequence] = after_validation
        elsif after_validation.class == Hash
          error_msg = ""
          after_validation.each do |key, error|
            error_msg += "#{error}\n"
          end
          redirect_to :controller => 'query', :action => 'result', params: params.merge(:notice => error_msg ).permit(:notice) and return
        end

      else
        redirect_to :controller => 'query', :action => 'result', params: params.merge(:notice => "Must provide an amino acid sequence in Fasta format").permit(:notice) and return
      end

      fasta_array = params[:sequence].scan(/>[^>]*/)
      # only allow one sequence at time on server
      if fasta_array.length > 1
        redirect_to :controller => 'query', :action => 'result', params: params.merge(:notice => "Please provide only one sequence.").permit(:notice) and return
      end

      # at this point, the params[:sequence] should be correct fasta format
      fasta_array = params[:sequence].scan(/>[^>]*/) 

      @hits = Hash.new
      @sequences = ActiveSupport::OrderedHash.new
      @new_customized_sequence = CustomizedProteinSequence.new
      protein_sequence = CustomizedProteinSequence.all
      @sequence_group = Hash.new
      protein_sequence.each do |s|
        @sequence_group[s.header] = s.group
      end
      @group_number_list = Array.new
      @organism_list = Array.new
      @fasta_seq = fasta_array[0]
      @query = Bio::FastaFormat.new( @fasta_seq )
      query_name = @query.definition
      @sequence = @query.to_seq
      @sequence.auto # Guess the type of sequence. Changes the class of @sequence.
      query_sequence_type = @sequence.seq.class == Bio::Sequence::AA ? 'protein' : 'gene'
      program = @sequence.seq.class == Bio::Sequence::AA ? 'blastp' : 'blastn'
      database = query_sequence_type == 'protein' ? 'reductive_dehalogenase_protein' : 'reductive_dehalogenase_gene'
      # sequence_class = query_sequence_type == 'protein'? ProteinSequence : NucleotideSequence
      blast_options = set_blast_options(program,params)
      blaster = Bio::Blast.local( program, "#{Rails.root}/index/blast/#{database}", blast_options)
      aa_report = blaster.query(@sequence.seq)
      @aa_similarity =  aa_report.hits().length.to_f / aa_report.db_num().to_f


      @is_exist_chain, @existing_matched_group = get_existing_groups(aa_report,@sequence.seq)
      @aa_sequence_result = generate_hit_array(aa_report,query_name,"protein")
      group_hash = Hash.new
      reversed_group_hash = Hash.new
      protein_sequence.each do |single_entry|
        if !@group_number_list.include? single_entry.group
          @group_number_list << single_entry.group
        end
        if !@organism_list.include? single_entry.organism

app/helpers/query_helper.rb
module QueryHelper

	def find_id_by_header(header)
		# puts "Header => #{header}"
		protein = CustomizedProteinSequence.find_by(:header => header)
		if !protein.nil?
			return protein.id
		else
			# what? why header will work... return nil will fail... what...
			return header
		end
	end

	def get_percentage_identity(hit)
		if hit.query_len > hit.query_seq.length
			match_identity = (hit.identity.to_f / hit.query_seq.length.to_f * 100).round(2)
		elsif hit.query_len < hit.query_seq.length
			match_identity = (hit.identity.to_f / hit.query_len.to_f * 100).round(2)
		elsif hit.query_len == hit.query_seq.length
			match_identity = (hit.identity.to_f / hit.query_len.to_f * 100).round(2)
		end
		return match_identity
	end

end

app/views/query/_phylogenies.html.erb
<div id="well-tree">
	<p id="_generate_tree">Click below to build a Phylogenetic Tree with your query sequence using <a href="http://www.drive5.com/muscle/"> MUSCLE </a> and <a href="http://phylocanvas.org/">Phylocanvas</a></p>

	<%= form_with url:'/phylogenetic_tree', remote: true,  :html => {:id => "do-tree"} do |f| %>
	
		<div class="container">
		  <div class="row">

		    <div class="col-4">Select OG group(s)</div>
		    <div class="col-8">Select Organism(s)</div>

		    <div class="w-100"></div>
		    <!-- increment stack here -->
		    <div class="col-4 stack-group"><%= f.select :group, options_for_select(@group_number_list.sort { |a,b| a && b ? a <=> b : a ? -1 : 1 }.map { |x| x == nil ? 'No Group' : x }), {:prompt => 'All OGs'}, :id => "orig-group" %></div>
		    <div class="col-8 stack-organism"><%= f.select :organism, options_for_select(@organism_list.sort { |a,b| a && b ? a <=> b : a ? -1 : 1 }.map { |x| x == nil ? 'No Organism' : x }), {:prompt => 'All Organism'}, :id => "orig-organism" %></div>

		    <div class="w-100"><hr></div>

		    <div class="col-4"><button id='add-group' type="button" >Add Group</button></div>
		    <div class="col-8"><button id='add-organism' type="button" >Add Organism</button></div>

		  </div>
		</div>

		<br>
		<%= f.text_area :form_sequence, :value => "#{@fasta_seq}", :style => "display:none;" %>
		<%= f.button 'Generate Phylogenetic Tree'.html_safe, :type => :submit, id: "generate-phylogenetic-tree", :class => "btn btn-primary" %>


	<% end %>


	<%# image_tag 'loading.gif', :id=> "waiting-gif", :style => "visibility:hidden;" %>
	
	<p id="phylocanvas-page-warning"></p>
	<div id="tree-group">
		<!-- phylocanvas tree will be rendered here -->
	</div>
	
	
	<p id="graph-note" style="visibility: hidden;">
		<hr>
		For more advanced graph viewer, please see <a href='https://en.wikipedia.org/wiki/List_of_phylogenetic_tree_visualization_software' target='_blank'> Wiki </a>
	</p>

</div>

app/views/query/_result.html.erb
<div>
<h3 id="seqresulttag"> BLASTP Results for <%= @query.definition %></h3>
<table class="each-result">

  <!--
  <tr>
    <th>Number of aligned sequences</th>
    <td>
      <%= @aa_sequence_result.length %>
    </td>
  </tr>
  -->
  

  <% if @identity_groups.length == 0 %>
    
    <tr>
      <th>Classification: Otholog group number</th>
      <td>No matching ortholog group</td>
    </tr>
    <tr>
      <th>Biochemically characterized members in group</th>
      <td>No matching characterized members</td>
    </tr>

  <% else %>

    <tr>
      <th>Classification: Otholog group number</th>
      <td>
        
        <% @identity_groups.each do |group_number| %>
          <%= form_with url:'protein',:class => "group-number-form", method: :get do |f| %>
            <%= hidden_field_tag(:group, group_number) %>
            <%= f.submit "#{group_number}", disabled: false, :id => 'group-click-button', formtarget: "_blank" %>
          <% end %>
          &nbsp;
        <% end %>
      </td>
    </tr>

    <tr>
      <th>Biochemically characterized members in group</th>
      <td>
        <!-- find the characterized member -->
        <% if @possible_group_number.length == 0 %>
          No matching characterized members
        <% else %>  
          <% @possible_group_number.each do |member| %>
            <%= link_to "#{member[1]}", protein_path(member[0]), target: "_blank" %> &nbsp;
          <% end %>
        <% end %>
      </td>
    </tr>

  <% end %>

  <tr>
    <th>Exists in Database</th>
    <td>
      <% if @is_exist_chain == false %>
        No
      <% else %>
        Yes
      <% end %>
    </td>
  </tr>

</table>
</div>
<hr id="hrtg">

app/views/query/_results_view.html.slim
div.container
  #seq-search-results
    - if @aa_sequence_result.present?
    
      - if @aa_sequence_result.length > 0
        - @aa_sequence_result.each do |sequence|
          .seq-search-hit
            .seq-search-scores
              | E value: #{sequence.evalue}
              br
              | Bit score: #{sequence.bit_score}
              br
              | Query length: #{sequence.query_seq.length}
              br
              | Identity: #{get_percentage_identity(sequence)} %
            .seq-search-title
              - if lookup_context.find_all('seq_search/_hit_link').any?
                = render '/seq_search/hit_link', sequence: sequence
              - else
                strong = link_to sequence.definition, protein_path(:id => find_id_by_header(sequence.definition)) , target: "_blank"
                br
                = form_with url:'protein', method: :get do |f|
                  = hidden_field_tag(:group, @sequence_group[sequence.definition])
                  | Group: 
                  - if @sequence_group[sequence.definition].present?
                    td = f.submit "#{@sequence_group[sequence.definition]}", disabled: false, formtarget: "_blank", :id => 'group-click-button'
                  - else
                    td No Group
                
            div
              .seq-search-sequence-labels
                br
                | Query:
                br
                br
                | Subject:
                br
              .seq-search-sequence-comparison
                - len = sequence.query_seq.length
                - query_seq = " " + sequence.query_seq
                - midline = " " + sequence.midline
                - subject = " " + sequence.target_seq
                - count = "1 "
                - offset = 1
                - for i in 2..len
                  - if i % 60 == 0
                    - count = count + " " + i.to_s
                    - query_seq.insert(i + offset, " " * i.to_s.size)
                    - midline.insert(i + offset, " " * i.to_s.size)
                    - subject.insert(i + offset, " " * i.to_s.size)
                    - offset = offset + i.to_s.size
                  - else
                    - count = count + " "
                - count = count + len.to_s
                - query_seq = query_seq + (" " * len.to_s.size)
                - midline = midline + (" "  * len.to_s.size)
                - subject = subject + (" "  * len.to_s.size)
                .seq-search-chain.seq-search-count= count
                .seq-search-chain.seq-search-query= query_seq
                .seq-search-chain.seq-search-midline= midline
                .seq-search-chain.seq-search-target= subject
        .data-container 
      - else
        p.alert.alert-danger No matches.

    - else
      p.alert.alert-danger No matches.

app/views/query/_submit_sequence.html.erb
<!-- send important field to backend, store the data into customized database -->
<!-- also send an email to our group about the new sequence -->
<!-- create the button in download that can download the new database package -->
<!-- also make download for graph happens -->

<!-- submit the param to function in query_controller by the url through ajax-->
<!-- do field validation in javascript -->
<!-- send request and get back the response -->
<!-- do all the backend at backend -->


<div class="well-submit-sequence">
	<p id="_submit_seq_p">
		Your RDase sequence does not belong to any of the ortholog groups currently in the database. In order to submit your sequence to our database automatically your sequence must be annotated as a reductive dehalogenase and made publicly available with an NCBI or IMG accession number. If you do not have an accession number, you can send the sequence directly to the <a href="https://www.labs.chem-eng.utoronto.ca/edwards/" target="_blank">Elizabeth Edwards Lab</a>. We will evaluate your sequence and add it to the database manually. Thank you for supporting the RDase Database!
		Your sequence match one of the RD_OD group in our database.
	</p>

	<%= form_with url:'/submit_sequence', remote: true, :html => {:id => "submit-seq"} do |f| %>
	  <%= f.text_field :name, placeholder: "Your Name (Required) ", :size=>"100", :required=>true %><br/>
	  <%= f.text_field :email, placeholder: "example@abc.com (Required) ", :size=>"100", :type=>"email",:required=>true %><br/>
	  <%= f.text_field :ncbi_accession_number, placeholder: "NCBI Accession Number (Required) ", :size=>"100", :type=>"text",:required=>true %><br/>
	  <%= f.text_field :dna, placeholder: "DNA Sequence in FASTA format (Optional)", :size=>"100" %><br/>
		<%= f.text_field :institution, placeholder: "Your Institution (Optional)", :size=>"100"%><br/>
		<%= f.text_field :publications, placeholder: "Citation (Optional)", :size=>"100" %><br/>
		<%= f.text_field :organism, placeholder: "Organism (Optional)", :size=>"100" %><br/>
		<%# recaptcha_tags :align => "center" %>
		<%= f.submit "Send", :class => "btn btn-primary", id: "submit-seq" %>
	<% end %>
	<h3 id="submit-message"></h3>


</div>

<script>

	$('#submit-seq').submit(function(e){
		e.preventDefault();
		var sequence = $('.seq-search-sequence').val();
		var group = $('#simtext-group').text().replace(/^\s+|\s+$/g, '');
		var form = $(this);
		form.attr('sequence',sequence);
		
		console.log(typeof(form.serialize()));
		$.ajax({
			type:"POST",
			url: "/submit_sequence",
			// 'form.serialize()+ '&sequence=' + sequence' is kind ugly but it works.
			data: form.serialize()+ '&sequence=' + sequence + '&group=' + group,
			success: function(data){
				console.log("success");
				console.log(data);
				$("#submit-message").text(data.message);
				$("#submit-seq").remove();
				$("#_submit_seq_p").remove();

			},
			error: function(data){
				$("#submit-message").text(data.message_err);
			}
		})
	})

</script>

app/views/query/result.html.slim
- if @error.present?
  - if @error.class == String
    p.alert.alert-danger
      = @error
  - elsif @error.class == Hash
    p.alert.alert-danger
      - @error.each do |key, array|
        = array

- elsif @aa_similarity.present?
  hr
  = render partial: "result"
  
  / .result-div
  /   #result-text
  /     p#result-textt 
  /     | #{link_to 'Submit your sequence to our database!', submit_sequence_path, target: '_blank'}
  /     p#result-textt
  /       a href="/help#how-to-construct-tree" target="_blank"  How the phylogenetic tree is constructed?
  /     hr
  /     = render partial: "phylogenies"
      
  = render partial: "results_view"
      
- elsif params[:commit].present?
  p.alert.alert-danger No Results

.modal

app/views/query/search.html.slim
  - content_for(:title) { "Classify Amino Acid Sequence" }
  - content_for(:description) { "Classify your amino acid sequence using Blast." }
  - if @error.present?
    .loading-animation
    - if @error.class == String
      p.alert.alert-danger
        = @error
    - elsif @error.class == Hash
      p.alert.alert-danger
        - @error.each do |key, array|
          = array
  
  .card
    .card-body
      h5.card-title
        | Enter the amino acid sequence of the reductive dehalogenase you would like to classify using
        | #{link_to ' FASTA format', 'http://en.wikipedia.org/wiki/Fasta_format', id: 'fasta-link', target: '_blank'}
      p.card-text
        = form_tag search_path(anchor: :results), id: 'seq-search-form' do
          .form-group
            = text_area_tag :sequence, params[:sequence], class: 'form-control seq-search-sequence'
          .form-group
            = submit_tag 'BLAST', class: 'btn btn-primary blast-btn'
            = button_tag 'Example', id: 'load-example', type: 'button', class: 'btn btn-link'
            = button_tag 'Reset', type: 'button', class: 'btn btn-link reset-btn', id: 'reset-button'

          / in the future, you can add more fieldset with more options
          .form-group
            i#blast-param-sign.fas.fa-plus
            span &nbsp;
            = button_tag "BLAST Parameters", :id => "blast-parameters", type: "button", class: 'btn btn-default'
            .row#parameter-box style=("display: none;")
              .col-md-4.col-sm-4
                .form-group
                  = label_tag :gap_cost, 'Cost to open a gap'
                  = text_field_tag :gap_cost, params[:gap_cost], class: 'form-control'
                .form-group
                  = label_tag :extend_cost, 'Cost to extend a gap'
                  = text_field_tag :extend_cost, params[:extend_cost], class: 'form-control'
              .col-md-4.col-sm-4
                .form-group
                  = label_tag :mismatch_penalty, 'Penalty for mismatch'
                  = text_field_tag :mismatch_penalty, params[:mismatch_penalty], class: 'form-control'
                .form-group
                  = label_tag :match_reward, 'Reward for match'
                  = text_field_tag :match_reward, params[:match_reward], class: 'form-control'
              .col-md-4.col-sm-4
                .form-group
                  = label_tag :evalue, 'Expectation value'
                  = text_field_tag :evalue, (params[:evalue]), class: 'form-control'
                .checkbox
                  = label_tag :new_result_tab, class: 'checkbox' do
                    = check_box_tag :new_result_tab, 1, params[:new_result_tab]
                    | Show result in new windows
                .checkbox
                  = label_tag :gapped_alignment, class: 'checkbox' do
                    = check_box_tag :gapped_alignment, 1, params[:gapped_alignment]
                    | Perform gapped alignment
                .checkbox
                  = label_tag :lower_case_filtering, class: 'checkbox' do
                    = check_box_tag :lower_case_filtering, 1, params[:lower_case_filtering]
                    | Lower case filtering of FASTA sequence
                .checkbox
                  = label_tag :filter_query_sequence, class: 'checkbox' do
                    = check_box_tag :filter_query_sequence, 1, params[:filter_query_sequence]
                    | Filter query sequence (DUST &amp; SEG)      

  - if @aa_similarity.present?
    .loading-animation
    hr
    = render partial: "result"
    .result-div
      #result-text
        p#result-textt 
        | #{link_to 'Submit your sequence to our database!', submit_sequence_path, :method => :get, target: '_blank'}
        p#result-textt
          a href="/help#how-to-construct-tree" target="_blank"  How phylogenetic tree (including user sequence) is constructed?
        hr
        = render partial: "phylogenies"
        
    = render partial: "results_view"


  - elsif params[:commit].present?
    p.alert.alert-danger No Results

  .modal